### ISSUE TITLE
Auto-Flags for add_arguments

### ISSUE THREAD

**Issue by JoschD** [pylhc/generic_parser#23]
The changes of #3 introduced a bug in `add_to_arguments` (entrypoint_parser.py):
When called with unknown opt, it still assumes that there are 'flags' given.
As they are only set in the Entrypoint-Class itself and not in the EntryPointParameters, this is not necessarily true.

Fix Suggestion 1: Add the auto-flagging to EntryPointParameters and force everyone to use these. (will require some rewrite of documentation, also some checks on the EntryPointParameters `__init__` and `add_arguments`)

Fix Suggestion 2: Add the flag-check to `add_to_arguments` (the easier and maybe better way)

**Comment by mihofer** [comment]
to fix, change line 538 to flag = params[key].get("flags", f"--{key}")
